# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-07 11:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_childrenproductcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketcampaigntranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.BasketCampaign'),
        ),
        migrations.AlterField(
            model_name='catalogcampaigntranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.CatalogCampaign'),
        ),
    ]
